name = "egadslite"
uuid = "8839a610-0e5e-4b77-8553-273f46a3dff9"
authors = ["XuliaDS <juliadocampo@gmail.com>"]
version = "0.1.0"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = ">=1.7"